[package]
name = "server"
version = "0.1.0"
edition = "2021"


[dependencies]
tokio = { version = "1.36.0", features = ["full"] }
tower-lsp = "0.20.0"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
